apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: greenearth-kibana-local
  namespace: greenearth-local
spec:
  version: 9.0.0
  count: 1
  elasticsearchRef:
    name: greenearth-es-local
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: 500m
