apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - elasticsearch.yaml
  - elasticsearch-internal-lb.yaml
  - kibana.yaml
  - deployment-state-configmap.yaml
  - elasticsearch-exporter.yaml
  - elasticsearch-node-sa.yaml
  - elasticsearch-snapshot-setup-job.yaml
  - templates/posts-index-template.yaml
  - templates/post-tombstones-index-template.yaml
  - templates/likes-index-template.yaml
  - templates/like-tombstones-index-template.yaml
  - templates/hashtags-index-template.yaml
  - templates/posts-alias.yaml
  - templates/post-tombstones-alias.yaml
  - templates/likes-alias.yaml
  - templates/like-tombstones-alias.yaml
  - templates/hashtags-alias.yaml
  - templates/inferences-index-template.yaml
  - templates/posts-ilm-index-template.yaml
  - templates/likes-ilm-index-template.yaml
  - templates/post-tombstones-ilm-index-template.yaml
  - templates/like-tombstones-ilm-index-template.yaml
  - update-recent-alias-cronjob.yaml

configMapGenerator:
  - name: snapshot-settings
    options:
      disableNameSuffixHash: true
    literals:
      - snapshot_bucket=
      - snapshot_schedule=
      - snapshot_expire_after=
      - snapshot_max_count=
  - name: index-settings
    options:
      disableNameSuffixHash: true
    literals:
      - index_shards=1
      - index_replicas=0
      - hashtag_index_shards=1
      - hashtag_index_replicas=0
      - inference_index_shards=1
      - inference_index_replicas=0
      - inference_max_age=1d
  - name: ilm-settings
    options:
      disableNameSuffixHash: true
    literals:
      - posts_index_shards=1
      - posts_index_replicas=0
      - likes_index_shards=1
      - likes_index_replicas=0
      - tombstones_index_shards=1
      - tombstones_index_replicas=0
      - posts_ilm_delete_age=30m
      - index_period=10min

configurations:
  - varreference.yaml

vars:
  - name: INDEX_SHARDS
    objref:
      kind: ConfigMap
      name: index-settings
      apiVersion: v1
    fieldref:
      fieldpath: data.index_shards
  - name: INDEX_REPLICAS
    objref:
      kind: ConfigMap
      name: index-settings
      apiVersion: v1
    fieldref:
      fieldpath: data.index_replicas
  - name: HASHTAG_INDEX_SHARDS
    objref:
      kind: ConfigMap
      name: index-settings
      apiVersion: v1
    fieldref:
      fieldpath: data.hashtag_index_shards
  - name: HASHTAG_INDEX_REPLICAS
    objref:
      kind: ConfigMap
      name: index-settings
      apiVersion: v1
    fieldref:
      fieldpath: data.hashtag_index_replicas
  - name: INFERENCE_INDEX_SHARDS
    objref:
      kind: ConfigMap
      name: index-settings
      apiVersion: v1
    fieldref:
      fieldpath: data.inference_index_shards
  - name: INFERENCE_INDEX_REPLICAS
    objref:
      kind: ConfigMap
      name: index-settings
      apiVersion: v1
    fieldref:
      fieldpath: data.inference_index_replicas
  - name: INFERENCE_MAX_AGE
    objref:
      kind: ConfigMap
      name: index-settings
      apiVersion: v1
    fieldref:
      fieldpath: data.inference_max_age
  - name: POSTS_INDEX_SHARDS
    objref:
      kind: ConfigMap
      name: ilm-settings
      apiVersion: v1
    fieldref:
      fieldpath: data.posts_index_shards
  - name: POSTS_INDEX_REPLICAS
    objref:
      kind: ConfigMap
      name: ilm-settings
      apiVersion: v1
    fieldref:
      fieldpath: data.posts_index_replicas
  - name: LIKES_INDEX_SHARDS
    objref:
      kind: ConfigMap
      name: ilm-settings
      apiVersion: v1
    fieldref:
      fieldpath: data.likes_index_shards
  - name: LIKES_INDEX_REPLICAS
    objref:
      kind: ConfigMap
      name: ilm-settings
      apiVersion: v1
    fieldref:
      fieldpath: data.likes_index_replicas
  - name: TOMBSTONES_INDEX_SHARDS
    objref:
      kind: ConfigMap
      name: ilm-settings
      apiVersion: v1
    fieldref:
      fieldpath: data.tombstones_index_shards
  - name: TOMBSTONES_INDEX_REPLICAS
    objref:
      kind: ConfigMap
      name: ilm-settings
      apiVersion: v1
    fieldref:
      fieldpath: data.tombstones_index_replicas
  - name: POSTS_ILM_DELETE_AGE
    objref:
      kind: ConfigMap
      name: ilm-settings
      apiVersion: v1
    fieldref:
      fieldpath: data.posts_ilm_delete_age
  - name: INDEX_PERIOD
    objref:
      kind: ConfigMap
      name: ilm-settings
      apiVersion: v1
    fieldref:
      fieldpath: data.index_period
