apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases/elasticsearch

patchesJson6902:
  - target:
      group: elasticsearch.k8s.elastic.co
      version: v1
      kind: Elasticsearch
      name: greenearth-es
      namespace: greenearth-prod
    path: patches/master-node-cpu.yaml
  - target:
      group: elasticsearch.k8s.elastic.co
      version: v1
      kind: Elasticsearch
      name: greenearth-es
      namespace: greenearth-prod
    path: patches/data-node-cpu.yaml