apiVersion: v1
kind: ConfigMap
metadata:
  name: posts-index-template
  namespace: greenearth-stage
data:
  posts-index-template.json: |
    {
      "index_patterns": ["posts_v1*"],
      "template": {
        "settings": {
          "number_of_shards": 1,
          "number_of_replicas": 0,
          "analysis": {
            "analyzer": {
              "content_analyzer": {
                "type": "standard",
                "stopwords": "_english_"
              }
            }
          }
        },
        "mappings": {
          "properties": {
            "at_uri": {
              "type": "keyword",
              "index": true
            },
            "author_did": {
              "type": "keyword",
              "index": true
            },
            "content": {
              "type": "text",
              "analyzer": "content_analyzer",
              "fields": {
                "raw": {
                  "type": "keyword",
                  "ignore_above": 10922
                }
              }
            },
            "created_at": {
              "type": "date",
              "format": "date_time||epoch_millis"
            },
            "thread_root_post": {
              "type": "keyword",
              "index": true
            },
            "thread_parent_post": {
              "type": "keyword",
              "index": true
            },
            "quote_post": {
              "type": "keyword",
              "index": true
            },
            "embeddings": {
              "type": "object",
              "properties": {
                "all_MiniLM_L12_v2": {
                  "type": "dense_vector",
                  "dims": 384,
                  "index": true,
                  "similarity": "cosine"
                },
                "all_MiniLM_L6_v2": {
                  "type": "dense_vector",
                  "dims": 384,
                  "index": true,
                  "similarity": "cosine"
                }
              }
            },
            "indexed_at": {
              "type": "date",
              "format": "date_time||epoch_millis"
            }
          }
        }
      }
    }
