apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: greenearth-es
  namespace: greenearth
spec:
  version: 9.0.0
  nodeSets:
  - name: masters
    count: 1
    config:
      node.roles: ["master"]
      # TODO: Enable mmap and increase vmem: https://www.elastic.co/docs/deploy-manage/deploy/cloud-on-k8s/virtual-memory
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  - name: data
    count: 2
    config:
      node.roles: ["data", "ingest"]
      # TODO: Enable mmap and increase vmem: https://www.elastic.co/docs/deploy-manage/deploy/cloud-on-k8s/virtual-memory
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi
              cpu: 500m
            limits:
              memory: 4Gi
              cpu: 2
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  http:
    tls:
      selfSignedCertificate:
        disabled: true