apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: greenearth-es-stage
  namespace: greenearth-stage
spec:
  version: 9.0.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.roles: ["master", "data", "ingest"]
      node.store.allow_mmap: true
    podTemplate:
      spec:
        initContainers:
        - name: sysctl-check
          image: docker.io/bash:5.2.21
          command: ['sh', '-c', 'sysctl vm.max_map_count']
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 12Gi
              cpu: "1500m"
            limits:
              memory: 12Gi
              cpu: "1500m"
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms6g -Xmx6g"
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
