apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: greenearth-kibana-stage
  namespace: greenearth-stage
spec:
  version: 9.0.0
  count: 1
  elasticsearchRef:
    name: greenearth-es-stage
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 2Gi
            cpu: "500m"
          limits:
            memory: 2Gi
            cpu: "500m"
