apiVersion: v1
kind: ConfigMap
metadata:
  name: hashtags-alias
data:
  hashtags-alias.json: |
    {
      "actions": [
        {
          "remove": {
            "index": "hashtags*",
            "alias": "hashtags",
            "must_exist": false
          }
        },
        {
          "add": {
            "index": "hashtags_v1",
            "alias": "hashtags",
            "is_write_index": true
          }
        }
      ]
    }
