apiVersion: v1
kind: ConfigMap
metadata:
  name: inferences-alias
data:
  inferences-alias.json: |
    {
      "actions": [
        {
          "add": {
            "index": "inferences_v1",
            "alias": "inferences"
          }
        }
      ]
    }
