apiVersion: v1
kind: ConfigMap
metadata:
  name: likes-ilm-index-template
data:
  likes-ilm-index-template.json: |
    {
      "index_patterns": ["likes-*"],
      "template": {
        "settings": {
          "number_of_shards": $(LIKES_INDEX_SHARDS),
          "number_of_replicas": $(LIKES_INDEX_REPLICAS),
          "refresh_interval": "30s",
          "translog.durability": "async",
          "translog.sync_interval": "30s",
          "lifecycle": {
            "name": "likes_ilm_policy"
          }
        },
        "mappings": {
          "_routing": {
            "required": true
          },
          "properties": {
            "at_uri": {
              "type": "keyword",
              "index": true
            },
            "subject_uri": {
              "type": "keyword",
              "index": true
            },
            "author_did": {
              "type": "keyword",
              "index": true
            },
            "created_at": {
              "type": "date",
              "format": "iso8601"
            },
            "indexed_at": {
              "type": "date",
              "format": "iso8601"
            }
          }
        }
      }
    }
