apiVersion: v1
kind: ConfigMap
metadata:
  name: likes-index-template
  namespace: greenearth-local
data:
  likes-index-template.json: |
    {
      "index_patterns": ["likes_v1*"],
      "template": {
        "settings": {
          "number_of_shards": 1,
          "number_of_replicas": 0
        },
        "mappings": {
          "properties": {
            "uri": {
              "type": "keyword",
              "index": true
            },
            "subject_uri": {
              "type": "keyword",
              "index": true
            },
            "author_did": {
              "type": "keyword",
              "index": true
            },
            "created_at": {
              "type": "date",
              "format": "iso8601"
            },
            "indexed_at": {
              "type": "date",
              "format": "iso8601"
            }
          }
        }
      }
    }
